FROM ubuntu:20.04

# ENTRYPOINT é um comando que é executado quando o container é iniciado e não pode ser substituído
ENTRYPOINT ["echo", "Hello "]

# Parâmetros que podem ser passados para o ENTRYPOINT
CMD ["World!"]