FROM node:20

WORKDIR /var/app

COPY app /var/app/

#COPY wait-for-it.sh /usr/local/bin/wait-for-it.sh
#RUN chmod +x /usr/local/bin/wait-for-it.sh

EXPOSE 3000

#ENTRYPOINT ["bash","/usr/local/bin/wait-for-it.sh", "db:3306", "--", "npm", "start", "dev" ]
ENTRYPOINT ["npm", "start", "dev" ]