services:
  laravel:
    build:
        context: ../laravel
        dockerfile: Dockerfile.prod
    container_name: laravel
    networks:
      - laranet
  nginx:
    image: vinicius91carvalho/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge